### ISSUE TITLE
Historisation des tickets

### ISSUE THREAD

**Issue by Netinq** [C0casio45/bot_onet#26]
# Contexte
Il est a l'heure impossible de pouvoir connaître le ticket qui a permis le bannissement d'un joueur. Nous devons chercher manuellement dans l'ensemble des tickets pour retrouver le ticket lié au bannissement.

# Backlog
Les cas de figures traités par la fonctionnalité sont les suivants :
- En tant que modérateur, je veux pouvoir retrouver le ticket qui a permis de sanctionner un joueur dans le message de bannissement dans le salon discord "ban", afin de pouvoir faciliter les tâches de modérations.

**Comment by C0casio45** [comment]
ça fait partie des prochaines features
