### ISSUE TITLE
:ambulance: Ban API issue

### ISSUE THREAD

**Issue by Netinq** [C0casio45/bot_onet#84]
L'API de ban n'est plus fonctionnelle. Le lien qu'elle utilise donne une erreur 404.

**Comment by C0casio45** [comment]
Peu tu me donner plus de contexte ?
![image](https://user-images.githubusercontent.com/50499894/172044708-0878ddbb-ab32-4421-b79a-31fd6a15d68e.png)

Perso elle marche très bien

![image](https://user-images.githubusercontent.com/50499894/172044717-4a844676-2a22-493e-8ea2-8536800fe2aa.png)
